package Task_2;

public class Ex extends Exception{
    public Ex(){
        System.out.println("проверяемое");
    }
}
